version: "3.9"

services:
  # 🐬 MySQL
  mysql_poliglota:
    image: mysql:8.0
    container_name: mysql_poliglota
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: poliglota_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - poliglota_net

  # ☸️ Cassandra
  cassandra_poliglota:
    image: cassandra:4.1
    container_name: cassandra_poliglota
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - poliglota_net

  # 🕸 Neo4j
  neo4j_poliglota:
    image: neo4j:5.22
    container_name: neo4j_poliglota
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/neo4jpoliglota
      - NEO4J_dbms_security_auth__minimum__password__length=4
    ports:
      - "7474:7474"  # Panel web
      - "7687:7687"  # Bolt (para conexión con Spring Boot)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - poliglota_net

networks:
  poliglota_net:

volumes:
  mysql_data:
  cassandra_data:
  neo4j_data:
  neo4j_logs:
