server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/poliglota?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j

  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: poliglota
    schema-action: create-if-not-exists
