spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poliglota_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: sensores
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: test1234

server:
  port: 8080
